Implement the function `vector_derivative_product` according to the instructions given in exercise 1.1d)

In [1]:
import numpy as np

# Implement this function without for loops but using broadcasting.
def vector_derivative_product(A, x):
    return A.reshape(-1, 1) * x

# The following code checks whether the implementation is correct.
A = np.random.uniform(size=(1, 64))
x = np.random.uniform(size=(32))
result = vector_derivative_product(A, x)
if result.shape != (A.shape[1], x.shape[0]):
    print('The result has the wrong shape.')
else:
    correct = True
    for i in range(result.shape[0]):
        for j in range(result.shape[1]):
            if result[i, j] != A[0, i] * x[j]:
                correct = False
                break
    print('The result is {} correct.'.format('' if correct else 'not'))
print(result)

The result is  correct.
[[0.31448152 0.30312211 0.02989722 ... 0.33712695 0.37956619 0.19439345]
 [0.20846152 0.20093166 0.01981808 ... 0.22347257 0.25160443 0.1288583 ]
 [0.26812862 0.25844353 0.02549053 ... 0.28743624 0.32362017 0.16574089]
 ...
 [0.32520233 0.31345567 0.03091643 ... 0.34861975 0.39250577 0.2010204 ]
 [0.00674187 0.00649835 0.00064094 ... 0.00722735 0.00813716 0.00416742]
 [0.0397908  0.03835351 0.00378284 ... 0.04265609 0.04802585 0.02459626]]
